#ifndef _SURFEL_BUILD_LAYOUT_
#define _SURFEL_BUILD_LAYOUT_

// Must match BUILD_HALF / BUILD_WORDS in global_illumination.rs
#define BUILD_HALF 32768u
#define BUILD_BLOCKS (BUILD_HALF / 256u)

#define HDR_RANGE_COUNT 0u
#define HDR_HOLE_COUNT 1u

#define OFF_BLOCK_SUMS 8u
#define OFF_BLOCK_EXCL (OFF_BLOCK_SUMS + BUILD_BLOCKS)
#define OFF_HOLES (OFF_BLOCK_EXCL + BUILD_BLOCKS)
#define OFF_IDS_A (OFF_HOLES + BUILD_HALF)
#define OFF_IDS_B (OFF_IDS_A + BUILD_HALF)
#define OFF_RANGES (OFF_IDS_B + BUILD_HALF)
#define RANGE_STRIDE 4u
#define RANGE_CAP (BUILD_HALF / 2u)
#define OFF_RANGES_NEXT (OFF_RANGES + RANGE_CAP * RANGE_STRIDE)
#define OFF_PENDING (OFF_RANGES_NEXT + RANGE_CAP * RANGE_STRIDE)
#define PENDING_STRIDE 8u
#define BUILD_WORDS (OFF_PENDING + RANGE_CAP * PENDING_STRIDE)

#endif
