[package]
name = "vulkan_framework_sdl2_glue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkan_framework = { path = "../vulkan_framework" }
sdl2-sys = "*"
