[package]
name = "vulkan_framework"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.37.3" # +1.3.238
smallvec = "1.10.0"
parking_lot = "0.12.1"